Bugfix for Sentry Deployment
Project-IS12/IS12-Warfare pull request #99
Opened 2024-06-01 20:31 UTC by warbluke

Most warfare turfs are climbable even if you're not in a trench, so you were able to escape a deployed sentry while still having it be deployed to make an invisible trap. Now you can't climb with a sentry in your hands (deployed or undeployed) and putting it on your back undeploys it. That should fix any loopholes to escape a deployed sentry without it undeploying.

2024-06-01 22:00 UTC, mattmatterson111 requested changes

2024-06-01 22:00 UTC, mattmatterson111 commented on code/game/gamemodes/warfare/turfs.dm
> +		//if(locate(/obj/item/storage) in user)//Gotta check storage as well.
Just delete this code. Don't leave it commented out.

2024-06-01 22:00 UTC, mattmatterson111 commented on code/modules/projectiles/guns/projectile/mattguns.dm
> +//	can_climb(user) = FALSE
Same here.

2024-06-01 22:00 UTC, mattmatterson111 commented on code/modules/projectiles/guns/projectile/mattguns.dm
> +	//can_climb(user) = TRUE
And here.

2024-06-01 22:00 UTC, mattmatterson111 commented on code/modules/projectiles/guns/projectile/mattguns.dm
> +	*/
And here.

2024-06-02 03:11 UTC, warbluke reviewed
Fixed, sorry for inconvenience

2024-06-04 04:47 UTC, merged

2024-06-04 04:47 UTC, mattmatterson111 commented
We ride again.